"""
Django settings for pbird project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# DJANGO FILES
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY THIS KEY IS FOR THE COMMUNCATION SENDGRID EMAIL
SENDGRID_API_KEY = config("SENDGRID_API_KEY")

# SECURITY THIS KEY IS FOR ENCRYPTION SIGNATURE
ENCRYPTION_KEY = config("ENCRYPTION_KEY", cast=int)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "phonenumber_field",
    "corsheaders",
    "knox",
    "api",
    "drf_yasg",
    "ckeditor",
    "django_filters",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("knox.auth.TokenAuthentication",),
    "DEFAULT_PAGINATION_CLASS": "pbird.pagination.CustomPagination",
}

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.AllowAllUsersModelBackend",)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "pbird.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pbird.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "NAME": config("DATABASE_NAME"),
        "ENFORCE_SCHEMA": config("DATABASE_ENFORCE_SCHEMA", cast=bool),
        "CLIENT": {"host": config("DATABASE_CLIENT_HOST")},
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")


# MEDIA CONFIG

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "api.CustomUser"

ACCOUNT_AUTHENTICATION_METHOD = "phone_number"

ACCOUNT_USERNAME_REQUIRED = False


# DIPLOY CONFIG

BACKEND_ROOT_URL = config("BACKEND_ROOT_URL")
BACKEND_IP_ADDRESS = config("BACKEND_IP_ADDRESS")
FRONTEND_ROOT_URL = config("FRONTEND_ROOT_URL")
SERVER_IP_ADDRESS = config("SERVER_IP_ADDRESS")
HTTP_IP_ADDRESS = config("HTTP_IP_ADDRESS")
HTTPS_IP_ADDRESS = config("HTTPS_IP_ADDRESS")

ALLOWED_HOSTS = [
    SERVER_IP_ADDRESS,
    HTTP_IP_ADDRESS,
    HTTPS_IP_ADDRESS,
    BACKEND_IP_ADDRESS,
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [FRONTEND_ROOT_URL, BACKEND_ROOT_URL]
CORS_ORIGIN_REGEX_WHITELIST = [FRONTEND_ROOT_URL, BACKEND_ROOT_URL]


# TWILIO CONFIG

TWILIO_SID = config("TWILIO_SID")
TWILIO_TOKEN = config("TWILIO_TOKEN")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER")
